### ISSUE TITLE
Fix: 모바일 환경의 질문 말풍선 끄트머리 위치

### ISSUE THREAD

**Issue by kdh8219** [Squarecat-meow/neo-quesdon#13]
![Screenshot_20241117_224353_Firefox](https://github.com/user-attachments/assets/25bbfab9-b317-4563-9865-4705cb7c5965)   
삐져나와있습니다
Device: Galaxy S23
Browser: Firefox 132.0 (Build #2016051567)

**Comment by yunochi** [comment]
그게 아까전 답변삭제 기능 추가하면서 새로 생긴 문제 같아요ㅠㅠ
내일 고쳐볼예정

**Comment by Squarecat-meow** [comment]
이번 풀리퀘에서 고쳤습니다 리뷰 후 머지할 예정
