### ISSUE TITLE
🐛  Login Form에 바로 enter쳤을때의 required 에러

### ISSUE THREAD

**Issue by yunochi** [Squarecat-meow/neo-quesdon#25]
### 마지막으로 사용한 인스턴스 도메인을 기억하는 기능의 수정
* 로그인 화면에서 마지막에 사용한 인스턴스가 자동완성된 상태에서 포커스 이동 없이 곧바로 엔터를 누를 경우 입력되지 않았다고 오류가 뜨는 버그 해결

**Comment by kdh8219** [comment]
앗 늦게라도 이슈 여는게 나았었군요... 감사합니다

**Comment by Squarecat-meow** [comment]
머지했씀돠~
